version: "3.7"
services:
  airflow-postgres:
    image: postgres:12
    hostname: airflow-postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-log:/var/log/postgresql

  airflow-webserver:
    image: ${AIRFLOW_DOCKER_IMAGE_NAME}:${AIRFLOW_DOCKER_IMAGE_TAG}
    build:
      args:
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
    hostname: airflow-webserver
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    restart: always
    depends_on:
      - airflow-postgres
    environment:
      - AIRFLOW_FERNET_KEY
      - HOST_ROOT_FOLDER
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
    volumes:
      - ${AIRFLOW_DAG_DIR}:/home/airflow/dags
      - $PWD/data:/home/airflow/data
      - $PWD/logs:/home//airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    ports:
      - "4080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  pg-data: {}
  pg-log: {}
